"""P-1.4 THE LEARNED ARM: search an unbounded space and pay for exactly ONE test.

This is the answer to Jim's question about using learned models to "shake out meaning",
and to the deeper problem behind every null in this program.

THE PROBLEM IT SOLVES. Every arm so far can only find a pattern SOMEONE THOUGHT TO
DECLARE. Declare more and multiplicity eats the signal: the mass screen paid a null 95th
percentile of 4.77 to look at 3,000 cells, which costs about 1.5 sigma against any single
effect. And each declared statistic compresses thousands of events into one number,
throwing away nearly all of the per-event information -- a resultant length cannot
represent "high tidal stress AND shallow AND within a week of a nearby M4", which is
exactly the shape a conditional mechanism would take.

A learned model has neither limitation, and it escapes multiplicity for a reason that is
sound rather than convenient: **all of the searching happens during training, on data
where nothing is being claimed. The test is a single number computed once on data the
model has never seen.** One look, one p, however vast the space searched to get there.

=======================================================================
THE DESIGN, and every choice below exists to close a specific loophole.
=======================================================================

MATCHED CASE-CONTROL, NOT RATE PREDICTION. Each real event contributes itself as a CASE
and K phantom times as CONTROLS, drawn from its OWN dwell null: same site, same +/- one
fortnight neighbourhood. The classifier's job is to tell the real time from the phantom
times.

This matching is what makes the result interpretable. Because a case and its controls
share a site and a two-week window, the model CANNOT win by learning where earthquakes
happen, or that some years are busier, or that clustering exists. All of that is identical
within a stratum. It can only win by finding structure in WHEN, at scales shorter than a
fortnight, which is precisely the hypothesis space this program cares about and could not
previously search.

THE NESTED COMPARISON, which is how the diurnal artifact is disarmed rather than avoided.
`exp_diurnal_discriminator.py` established that roughly 2 percent of catalogued events are
displaced into local night by cultural noise. A learned model turned loose on this data
will find that first and look brilliant. So two models are fitted:

    MODEL A (nuisance)   local solar hour, day of week, day of year -- the observer block
    MODEL B (full)       everything in A, PLUS the lunar and tidal block

**The declared statistic is the improvement of B over A**, out of sample. Model A is
handed the artifact for free, so B can only win by finding something the artifact does not
already explain. This is strictly better than dropping to M >= 2.5 to escape the artifact,
which would throw away 90 percent of the sample we just gained.

THE NULL, because a black-box improvement has no analytic distribution. Under H0 a case
and its own controls are exchangeable, so the null is generated by PERMUTING THE LABELS
WITHIN EACH STRATUM and refitting both models end to end. That regenerates the entire
pipeline -- both fits, the same hyperparameters, the same split -- so anything the
procedure manufactures on its own appears in the null too. It is expensive, and it is the
only honest option.

THE SPLIT. Training and evaluation both live inside the EXPLORATION portion, split
temporally so that no stratum straddles the boundary. **The holdout is not touched.** If
the declared statistic fires, the holdout is where it goes next, and that is a separate
decision for Jim because the holdout is spent once.

WHAT A WIN WOULD AND WOULD NOT MEAN. A win says something in the tidal block carries
information about event timing beyond the observer block. It does NOT say what, or with
what sign, or through what mechanism. Attribution is a separate stage and is not attempted
here -- a model that predicts is not a model that explains, and conflating the two is how
this field generates retractions.

PRICED 1.
"""

from __future__ import annotations

import datetime as _dt
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import exp_highn as HN
import exp_mass_screen as MS
import exp_world_harmonics as W

from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import roc_auc_score, log_loss

OUT_JSON = HERE / "results_learned.json"
ZEN = HERE / "data" / "xue_lu_zenodo"

CONTROLS_PER_CASE = 4
NULL_HALF_WINDOW_DAYS = MS.FORTNIGHT_DAYS
TRAIN_FRAC = 0.70
N_PERMUTATIONS = 40
RNG_SEED = 20260822

NUISANCE = ["solar_hour_sin", "solar_hour_cos", "dow_sin", "dow_cos",
            "doy_sin", "doy_cos"]
TIDAL = ["areal", "areal_abs", "shear", "rate", "rate_abs",
         "moon_sinel", "moon_dist", "elong_cos",
         "moon_ha_sin", "moon_ha_cos", "moon_az_sin", "moon_az_cos",
         "bearing_sin2", "bearing_cos2"]


def build_features(t_days, lat, lon):
    r = MS.raw_series(t_days, lat, lon)
    jd = t_days + W.UNIX_EPOCH_JD
    sun_ha = MS.TT.body_direction(jd, np.zeros_like(lon), lon, 0.0,
                                  "sun")["hour_angle_rad"]
    dow = np.mod(t_days + 4.0, 7.0) * (2 * np.pi / 7.0)      # arbitrary phase, consistent
    doy = np.mod(t_days, 365.2422) * (2 * np.pi / 365.2422)
    cols = {
        "solar_hour_sin": np.sin(sun_ha), "solar_hour_cos": np.cos(sun_ha),
        "dow_sin": np.sin(dow), "dow_cos": np.cos(dow),
        "doy_sin": np.sin(doy), "doy_cos": np.cos(doy),
        "areal": r["areal"], "areal_abs": r["areal_abs"], "shear": r["shear"],
        "rate": r["rate"], "rate_abs": r["rate_abs"],
        "moon_sinel": r["moon_sinel"], "moon_dist": r["moon_dist"],
        "elong_cos": r["elong_cos"],
        "moon_ha_sin": np.sin(r["moon_hourangle"]),
        "moon_ha_cos": np.cos(r["moon_hourangle"]),
        "moon_az_sin": np.sin(r["moon_az"]), "moon_az_cos": np.cos(r["moon_az"]),
        "bearing_sin2": np.sin(r["bearing"]), "bearing_cos2": np.cos(r["bearing"]),
    }
    return cols


def fit_score(X_tr, y_tr, X_te, y_te, seed):
    m = HistGradientBoostingClassifier(
        max_iter=200, learning_rate=0.06, max_leaf_nodes=31,
        min_samples_leaf=100, l2_regularization=1.0,
        early_stopping=True, validation_fraction=0.15,
        random_state=seed)
    m.fit(X_tr, y_tr)
    p = m.predict_proba(X_te)[:, 1]
    return float(roc_auc_score(y_te, p)), float(log_loss(y_te, p))


def main():
    rng = np.random.default_rng(RNG_SEED)
    t, la, lo, dp, mg = HN.load_zenodo(ZEN / "QTM_decluster_m0.1.txt")
    MS.assert_epoch(t, 2008, "QTM_declustered")
    t, la, lo, dp, mg, n_hold = HN.split(t, la, lo, dp, mg)
    n = t.size
    print("QTM declustered exploration: %d events (%d holdout reserved)"
          % (n, n_hold), flush=True)

    K = CONTROLS_PER_CASE
    off = rng.uniform(-NULL_HALF_WINDOW_DAYS, NULL_HALF_WINDOW_DAYS, size=(n, K))
    t_all = np.concatenate([t, (t[:, None] + off).ravel()])
    la_all = np.concatenate([la, np.repeat(la, K)])
    lo_all = np.concatenate([lo, np.repeat(lo, K)])
    y = np.concatenate([np.ones(n), np.zeros(n * K)])
    stratum = np.concatenate([np.arange(n), np.repeat(np.arange(n), K)])

    print("building features for %d rows ..." % t_all.size, flush=True)
    cols = build_features(t_all, la_all, lo_all)
    Xa = np.column_stack([cols[c] for c in NUISANCE])
    Xb = np.column_stack([cols[c] for c in NUISANCE + TIDAL])

    # temporal split by STRATUM so no case is separated from its own controls
    order = np.argsort(t)
    cut = order[int(TRAIN_FRAC * n)]
    train_strata = np.zeros(n, dtype=bool)
    train_strata[t < t[cut]] = True
    tr = train_strata[stratum]
    te = ~tr
    print("  train rows %d   test rows %d   (test cases %d)"
          % (tr.sum(), te.sum(), int(y[te].sum())), flush=True)

    auc_a, ll_a = fit_score(Xa[tr], y[tr], Xa[te], y[te], 0)
    auc_b, ll_b = fit_score(Xb[tr], y[tr], Xb[te], y[te], 0)
    d_auc = auc_b - auc_a
    d_ll = ll_a - ll_b
    print("  MODEL A (nuisance only): AUC %.5f  logloss %.6f" % (auc_a, ll_a), flush=True)
    print("  MODEL B (with tidal)   : AUC %.5f  logloss %.6f" % (auc_b, ll_b), flush=True)
    print("  observed dAUC = %+.5f   dLogLoss = %+.6f" % (d_auc, d_ll), flush=True)

    print("\ngenerating null by within-stratum label permutation "
          "(%d refits of BOTH models) ..." % N_PERMUTATIONS, flush=True)
    null_dauc, null_dll = [], []
    for i in range(N_PERMUTATIONS):
        r2 = np.random.default_rng(RNG_SEED + 1000 + i)
        yp = np.zeros_like(y)
        # within each stratum, one of the K+1 members is relabelled as the case
        pick = r2.integers(0, K + 1, size=n)
        yp[np.arange(n)[pick == 0]] = 1.0
        nz = pick > 0
        yp[n + np.arange(n)[nz] * K + (pick[nz] - 1)] = 1.0
        a1, l1 = fit_score(Xa[tr], yp[tr], Xa[te], yp[te], i + 1)
        b1, l2 = fit_score(Xb[tr], yp[tr], Xb[te], yp[te], i + 1)
        null_dauc.append(b1 - a1)
        null_dll.append(l1 - l2)
        if (i + 1) % 10 == 0:
            print("    %d/%d  null dAUC so far: mean %+.5f sd %.5f"
                  % (i + 1, N_PERMUTATIONS, np.mean(null_dauc), np.std(null_dauc)),
                  flush=True)

    null_dauc = np.asarray(null_dauc)
    p_auc = float((np.sum(null_dauc >= d_auc) + 1) / (N_PERMUTATIONS + 1))
    p_ll = float((np.sum(np.asarray(null_dll) >= d_ll) + 1) / (N_PERMUTATIONS + 1))

    out = {
        "arm": "P-1.4 learned arm: matched case-control, nested model comparison",
        "generated_utc": _dt.datetime.now(_dt.timezone.utc).isoformat(),
        "priced_tests": 1, "holdout_touched": False,
        "catalogue": "QTM_decluster_m0.1 exploration split",
        "n_cases": int(n), "controls_per_case": K,
        "n_holdout_reserved": int(n_hold),
        "design": ("each event contributes itself as a case and K phantom times from its "
                   "OWN dwell null (same site, same +/- fortnight); a case and its "
                   "controls share site, epoch and rate, so the model can only win by "
                   "finding structure in WHEN at sub-fortnight scales"),
        "model_A_features": NUISANCE, "model_B_features": NUISANCE + TIDAL,
        "why_nested": ("model A is handed the day/night detection artifact for free, so B "
                       "can only win by finding what the artifact does not explain"),
        "model_A": {"auc": auc_a, "log_loss": ll_a},
        "model_B": {"auc": auc_b, "log_loss": ll_b},
        "declared_statistic_delta_auc": d_auc,
        "delta_log_loss": d_ll,
        "null": {"kind": "within-stratum label permutation, BOTH models refitted",
                 "n_permutations": N_PERMUTATIONS,
                 "null_delta_auc_mean": float(null_dauc.mean()),
                 "null_delta_auc_sd": float(null_dauc.std(ddof=1)),
                 "null_delta_auc_p95": float(np.quantile(null_dauc, 0.95))},
        "p_delta_auc": p_auc, "p_delta_log_loss": p_ll,
    }
    out["verdict"] = (
        ("CANDIDATE. The tidal block improves out-of-sample discrimination beyond the "
         "observer block, dAUC = %+.5f against a permutation null (p = %.4f). This is a "
         "single declared test and it fired. It says SOMETHING in the tidal covariates "
         "carries timing information; it does NOT say what, with what sign, or by what "
         "mechanism. Next step is attribution, and then the holdout -- which is Jim's "
         "call, because it is spent once." % (d_auc, p_auc))
        if p_auc <= 0.05 else
        ("NULL. dAUC = %+.5f against a permutation null (p = %.4f). A model given the "
         "full per-event tidal vector, free to represent any interaction, and searched "
         "without multiplicity cost, does not beat a model that knows only the time of "
         "day. That is a substantially stronger statement than any binned null this "
         "program has produced, because it forecloses the whole space at once rather "
         "than one declared statistic at a time." % (d_auc, p_auc)))
    OUT_JSON.write_text(json.dumps(out, indent=2, default=float), encoding="utf-8")
    print("\n" + "=" * 78)
    print("  observed dAUC %+.5f   null mean %+.5f sd %.5f   p = %.4f"
          % (d_auc, null_dauc.mean(), null_dauc.std(ddof=1), p_auc))
    print("\n" + out["verdict"])
    print("\nwrote %s" % OUT_JSON.name)


if __name__ == "__main__":
    main()
