"""EQ-24 miner v2 throughput layer: parallelism, RNG policy and the ladder.

The four things this file exists to prevent:

  a. a "speedup" that quietly changed the sequential numbers. `--jobs 1` must be
     the v1 code path to the last bit, so the v1 inner loops are RE-STATED VERBATIM
     here and compared against the refactored task bodies. If someone edits
     `glm_task` and the pin still passes, the edit was genuinely behaviour-neutral.
  b. a parallel result that depends on how the pool happened to schedule. Same
     inputs at --jobs 2 and --jobs 4 must give the same numbers, bit for bit.
  c. a ladder p-value that is fast and wrong. Checked against a case whose exact
     p-value is known in closed form, plus the stopping rule's own invariants.
  d. a resumed parallel run that recomputes, double-counts, or silently drops a
     task. Plus: a worker that raises must name the failing feature/test upward.
"""

from __future__ import annotations

import datetime as _dt
import json
import math
import os

import numpy as np
import pytest

from engine import mine as M, mine_session as ms

SEED = 20260811
N_DAYS = 900
N_SURR = 40


# ------------------------------------------------------------------ fixtures ---
def _payload(n_feats=3, n_surr=N_SURR, ladder=None, seed=SEED):
    """A small but REAL payload: real ephemeris features, synthetic target."""
    t0 = _dt.datetime(2000, 1, 1)
    feats = M.ephemeris_features(t0, N_DAYS)[:n_feats]
    rng = np.random.default_rng(3)
    offset = np.full(N_DAYS, 5.0)
    counts = rng.poisson(offset).astype(np.float64)
    window = slice(0, N_DAYS)
    n_ev = 600
    day = np.sort(rng.integers(0, N_DAYS, size=n_ev))
    marks = {"day": day, "day_float": day + rng.random(n_ev),
             "mag": 4.5 + rng.exponential(0.4, n_ev),
             "depth": rng.uniform(0.0, 30.0, n_ev)}
    cfg = {"n_periods": 120, "n_peaks": 3, "seed": seed}
    return {
        "feats": {f.name: f for f in feats}, "window": window,
        "counts": counts, "offset": offset,
        "days": np.arange(N_DAYS, dtype=np.float64), "resid": counts - offset,
        "marks": marks, "fe_day": day - window.start,
        "seed": seed, "n_surr": n_surr, "ladder": ladder, "cfg": cfg,
        "period_chunk": M.PERIOD_SURROGATE_CHUNK,
    }


def _keys(W):
    return ([f"glm:{n}" for n in W["feats"]]
            + [f"marks:{n}" for n in W["feats"]]
            + ms.period_task_keys(W["cfg"], W["n_surr"]))


def _ckpt(tmp_path, name="session_x"):
    return ms.Checkpoint(str(tmp_path / name / "checkpoint.json"),
                         {"preset": "unit"}, "unit-hash")


# ============================================================================
# (a) REGRESSION PIN -- --jobs 1 is the v1 code path, verbatim
# ============================================================================
def test_jobs1_glm_is_bit_identical_to_the_v1_inner_loop():
    """The v1 GLM loop, restated here verbatim, must equal `glm_task`.

    This is the audit baseline. It is written out longhand ON PURPOSE: a golden
    JSON blob would pin the numbers but would not show a future reader WHAT the
    baseline was, and could be regenerated by whoever broke it.
    """
    W = _payload()
    counts, offset, window, n_surr = (W["counts"], W["offset"], W["window"],
                                      W["n_surr"])

    for f in W["feats"].values():
        # ---- v1, copied from mine_session.run() before the v2 refactor ----
        rng_v1 = np.random.default_rng(SEED)
        v1 = []
        for lag in f.lags:
            X = f.design(window, lag)
            fit = M.glm_fit(X, counts, offset)
            S = M.score_stat_all_shifts(X, counts, offset)
            p_shift, n_used = M.empirical_p(S, n_surr, rng_v1)
            Sb = M.score_stat_block_bootstrap(X, counts, offset, n_surr, rng_v1,
                                              mean_block=f.block_days)
            p_boot = M.bootstrap_p(S[0], Sb)
            p = p_boot if f.periodic else max(p_shift, p_boot)
            b = np.asarray(fit["beta"])
            amp = float(np.hypot(*b)) if f.kind == "phase" else float(abs(b[0]))
            v1.append({
                "feature": f.name, "family": f.family, "kind": f.kind,
                "lag": int(lag), "test": "glm_poisson_offset_etas", "df": f.df,
                "beta": fit["beta"], "se": fit["se"], "amplitude_log_rate": amp,
                "pct_rate_modulation": 100.0 * (math.exp(amp) - 1.0),
                "bits_per_event": fit["bits_per_event"],
                "chi2_score": float(S[0]), "p_parametric": M.chi2_sf(S[0], f.df),
                "p_circular_shift": p_shift, "p_block_bootstrap": p_boot,
                "block_days": f.block_days,
                "null": ("block-bootstrap (periodic feature)" if f.periodic
                         else "max(circular-shift, block-bootstrap)"),
                "p_raw": p, "n_surrogates": min(n_used, n_surr),
                "converged": fit["converged"],
            })

        # ---- v2, sequential path: the SAME shared-rng threading ----
        rng_v2 = np.random.default_rng(SEED)
        v2 = ms.glm_task(f, window, counts, offset, n_surr, lambda lag: rng_v2,
                         None, seed=SEED)
        assert json.dumps(v1, sort_keys=True) == json.dumps(v2, sort_keys=True), \
            f"--jobs 1 GLM output drifted from v1 for {f.name}"


def test_jobs1_marks_and_period_are_bit_identical_to_the_v1_inner_loops():
    W = _payload(n_feats=2)
    counts, offset, window = W["counts"], W["offset"], W["window"]
    marks, fe_day, n_surr = W["marks"], W["fe_day"], W["n_surr"]

    for f in W["feats"].values():
        rng_v1 = np.random.default_rng(SEED)
        vals = f.values[window][fe_day]
        v1 = []
        for mk in ("mag", "depth"):
            r = M.mark_test(vals, marks[mk], f.kind, n_surr, rng_v1)
            r.update({"feature": f.name, "family": f.family, "kind": f.kind,
                      "mark": mk, "n_events": int(marks[mk].size)})
            v1.append(r)
        rng_v2 = np.random.default_rng(SEED)
        v2 = ms.marks_task(f, window, fe_day, marks, n_surr, rng_v2, None,
                           seed=SEED)
        assert json.dumps(v1, sort_keys=True) == json.dumps(v2, sort_keys=True)

    # ---- period scan: PIN DELIBERATELY UPDATED IN v2 PHASE 1b ----
    # The v1 pin compared `period_scan` driven by a THREADED Generator against the
    # sequential driver threading the same one. That stream is gone on purpose: it
    # made the scan one indivisible task (90.7% of the sweep, Amdahl ceiling 1.10x)
    # and it was reproducible only for a single process running a fixed task order.
    # The replacement pin is stronger, not weaker -- it fixes the scan against the
    # KEY-DERIVED per-surrogate streams, which is a property of the seed alone and
    # holds across processes, chunkings and job counts (see the three phase-1b tests
    # at the bottom of this file).
    periods = np.exp(np.linspace(math.log(ms.PERIOD_MIN), math.log(ms.PERIOD_MAX),
                                 int(W["cfg"]["n_periods"])))
    peaks, meta = M.period_scan(W["days"], W["resid"], periods, n_surr, SEED,
                                n_peaks=int(W["cfg"]["n_peaks"]), verbose=False)
    v2 = ms.period_task(counts, offset, W["days"], W["resid"], W["cfg"], n_surr,
                        SEED, verbose=False)
    assert [p["period_days"] for p in v2["peaks"]] == [p["period_days"]
                                                       for p in peaks]
    assert [p["p_raw"] for p in v2["peaks"]] == [p["p_raw"] for p in peaks]
    assert v2["scan"]["ar1_phi"] == meta["ar1_phi"]
    # and the scan must refuse a threaded Generator outright rather than silently
    # accepting one and reintroducing order dependence
    with pytest.raises((TypeError, AttributeError, KeyError)):
        M.period_scan(W["days"], W["resid"], periods, n_surr,
                      np.random.default_rng(SEED), n_peaks=2, verbose=False)


def test_jobs_flag_is_absent_from_the_config_hash_and_ladder_is_present():
    """--jobs is execution; --ladder is statistics. The hash must say so."""
    from engine import splits

    class A:
        mag_target, dlat, dlon, explore_frac = 4.5, 0.5, 0.5, 0.7
        data_dir, no_download, seed, tranche1 = "engine/data", True, 1, False
        ladder = False
        ladder_h = ladder_chunk = None

    base = ms.build_config(A(), ms.QUICK)
    a2 = A()
    a2.jobs = 32                       # an execution knob; must not move the hash
    assert splits.config_hash(ms.build_config(a2, ms.QUICK)) == \
        splits.config_hash(base)
    assert "jobs" not in json.dumps(base)
    # and a default (ladder-off) config must be byte-identical to the v1 shape
    assert "ladder" not in base

    a3 = A()
    a3.ladder = True
    lad = ms.build_config(a3, ms.QUICK)
    assert lad["ladder"]["rule"] == "besag_clifford_1991"
    assert lad["ladder"]["h"] == 25
    assert lad["ladder"]["n_max"] == ms.QUICK["n_surrogates"]
    assert splits.config_hash(lad) != splits.config_hash(base), \
        "--ladder must change the config hash: it changes the sampling rule"

    a4 = A()
    a4.ladder, a4.ladder_h = True, 40
    assert splits.config_hash(ms.build_config(a4, ms.QUICK)) != \
        splits.config_hash(lad), "h must be part of the config hash"


# ============================================================================
# (b) PARALLEL DETERMINISM -- results independent of pool scheduling
# ============================================================================
@pytest.mark.parametrize("ladder", [None, dict(M.LADDER_DEFAULTS, n_max=N_SURR)])
def test_jobs2_and_jobs4_agree_bit_for_bit(tmp_path, ladder):
    W = _payload(ladder=ladder)
    keys = _keys(W)
    out = {}
    for jobs in (2, 4):
        ck = _ckpt(tmp_path, f"session_j{jobs}")
        ms._run_tasks_parallel(ck, keys, W, jobs, verbose=False)
        out[jobs] = ck.state["results"]
    assert set(out[2]) == set(keys)
    assert json.dumps(out[2], sort_keys=True) == json.dumps(out[4], sort_keys=True)


def test_parallel_matches_in_process_dispatch():
    """The pool must not be the thing that decides the answer."""
    W = _payload(n_feats=2)
    keys = _keys(W)
    direct = {k: ms.dispatch_task(k, W) for k in keys}
    ms._worker_init(W)
    viaworker = {}
    for k in keys:
        rk, res, err, secs = ms.worker_run_task(k)
        assert err is None, err
        assert secs >= 0.0
        viaworker[rk] = res
    assert json.dumps(direct, sort_keys=True) == json.dumps(viaworker,
                                                            sort_keys=True)


def test_task_seeds_are_key_derived_and_collision_checked():
    W = _payload()
    keys = [M.test_key(SEED, n, "glm", lag=0, null_type="block_bootstrap")
            for n in W["feats"]]
    keys += [M.test_key(SEED, n, "mark_mag", null_type="block_bootstrap")
             for n in W["feats"]]
    digests = ms.assert_task_keys_unique(keys)
    assert len(digests) == len(keys)

    # the schema carries region/bin_width NOW so adding strata later is not a
    # re-keying event for everything else
    assert set(M.TEST_KEY_FIELDS) == {"master_seed", "feature", "kind", "lag",
                                      "rung", "null_type", "region", "bin_width"}
    # and a genuine collision must be loud, not silent
    dup = keys + [keys[0]]
    with pytest.raises(RuntimeError, match="collision"):
        ms.assert_task_keys_unique(dup)

    # lag and null_type must actually move the stream
    a = ms.task_rng(SEED, "f", "glm", 0, null_type="block_bootstrap").random(4)
    b = ms.task_rng(SEED, "f", "glm", 1, null_type="block_bootstrap").random(4)
    c = ms.task_rng(SEED, "f", "glm", 0, null_type="circular_shift").random(4)
    assert not np.array_equal(a, b) and not np.array_equal(a, c)


def test_ladder_rung_streams_cross_process_boundaries():
    """Popper's condition: rung 2 is rung 2 however the rungs were split up.

    Runs the rungs three ways -- both in one call, rung 2 alone, and rung 2 after
    rung 1 was drawn by a SEPARATE process -- and requires identical draws.
    """
    import concurrent.futures as cf
    import multiprocessing as mp

    rr = ms.rung_rng_factory(SEED, "moon_synodic_phase", "glm", 0,
                             null_type="block_bootstrap")
    one_process = [rr(0).random(5), rr(1).random(5), rr(2).random(5)]
    # rung 2 drawn on its own, with rungs 0 and 1 never drawn at all
    alone = rr(2).random(5)
    assert np.array_equal(one_process[2], alone)

    ctx = mp.get_context("spawn")
    with cf.ProcessPoolExecutor(max_workers=2, mp_context=ctx) as ex:
        got = list(ex.map(_draw_rung, [0, 1, 2]))
    for i in range(3):
        assert np.array_equal(one_process[i], got[i]), \
            f"rung {i} differs across a process boundary"


def _draw_rung(i):
    """Module-level (spawn-safe) helper for the cross-process rung test."""
    rr = ms.rung_rng_factory(SEED, "moon_synodic_phase", "glm", 0,
                             null_type="block_bootstrap")
    return rr(i).random(5)


def test_reduction_order_is_key_determined_not_arrival_determined():
    """BH and the ranked table must not depend on the order results arrive in."""
    rows = [{"p_raw": 0.5, "order_key": [0, 0, 0, 0, "a"]},
            {"p_raw": 0.5, "order_key": [0, 1, 0, 0, "b"]},
            {"p_raw": 0.01, "order_key": [0, 2, 0, 0, "c"]},
            {"p_raw": 0.5, "order_key": [1, 0, -1, 0, "d"]}]
    shuffled = [rows[2], rows[0], rows[3], rows[1]]
    a = sorted(rows, key=lambda t: t["order_key"])
    b = sorted(shuffled, key=lambda t: t["order_key"])
    assert a == b

    # BH itself must be order-invariant, ties included
    p = np.array([0.5, 0.5, 0.01, 0.5])
    perm = np.array([2, 0, 3, 1])
    q1, s1 = M.benjamini_hochberg(p, 0.1)
    q2, s2 = M.benjamini_hochberg(p[perm], 0.1)
    assert np.allclose(q1[perm], q2) and (s1[perm] == s2).all()


# ============================================================================
# (c) LADDER CORRECTNESS
# ============================================================================
def test_ladder_p_matches_a_known_closed_form_p():
    """A case whose p-value is known exactly, checked two ways.

    The observed statistic is placed at the exact q-quantile of a null we control,
    so the true exceedance probability IS q. The ladder's estimate must land on it,
    and the estimator's own spread must match the theory for h/l (whose relative SD
    is 1/sqrt(h)) -- a ladder that returned a constant would pass a mean check.
    """
    rng = np.random.default_rng(1234)
    for q in (0.5, 0.1, 0.02):
        s_obs = 1.0 - q                       # P(U(0,1) >= 1-q) = q, exactly
        est = []
        for i in range(400):
            ss = M.seed_sequence_for(
                M.test_key(SEED, f"known_{q}_{i}", "glm", lag=0, null_type="mc"))
            est.append(M.besag_clifford_p(
                lambda b, g: g.random(b), s_obs, n_max=5000,
                rung_rng=lambda r, _s=ss: np.random.default_rng(
                    M.rung_seed_sequence(_s, r)))["p"])
        est = np.array(est)
        # theory for the sequential estimator h/l: SD = q*sqrt((1-q)/h)
        sd_theory = q * math.sqrt((1.0 - q) / 25.0)
        se = sd_theory / math.sqrt(est.size)
        assert abs(est.mean() - q) < 5.0 * se, \
            f"ladder p mean {est.mean():.5f} != true q {q} (5 SE = {5 * se:.5f})"
        # the SPREAD must match the theory too: a rule that returned a constant,
        # or one that was secretly drawing far more than h exceedances, would pass
        # the mean check and fail here.
        assert 0.5 * sd_theory < est.std() < 2.0 * sd_theory, \
            (f"ladder p spread {est.std():.5f} does not match the h/l theory "
             f"{sd_theory:.5f} at q={q}")
    assert rng is not None


def test_ladder_stopping_rule_invariants():
    ss = M.seed_sequence_for(M.test_key(SEED, "inv", "glm", lag=0, null_type="mc"))

    def rr(r):
        return np.random.default_rng(M.rung_seed_sequence(ss, r))

    # early stop: p = h/l exactly, and l is the index of the h-th exceedance
    hot = M.besag_clifford_p(lambda b, g: g.random(b), 0.0, n_max=1000,
                             rung_rng=rr, h=25, chunk=200)
    assert hot["l_stop"] == 25 and hot["p"] == 25 / 25.0
    assert hot["p_basis"].startswith("h/l")

    # cap reached with c < h: the ordinary fixed-sample estimate, and NOT h/l
    cold = M.besag_clifford_p(lambda b, g: g.random(b), 2.0, n_max=1000,
                              rung_rng=rr, h=25, chunk=200)
    assert cold["l_stop"] is None and cold["n_exceed"] == 0
    assert cold["p"] == pytest.approx(1.0 / 1001.0)
    assert cold["n_drawn"] == 1000

    # chunk size is an implementation detail: it must not change the answer
    a = M.besag_clifford_p(lambda b, g: g.random(b), 0.9, n_max=2000, rung_rng=rr,
                           h=25, chunk=200)
    assert 0.0 < a["p"] <= 1.0
    # the h-th exceedance index must never exceed the number drawn
    assert a["l_stop"] is None or a["l_stop"] <= a["n_drawn"]
    with pytest.raises(ValueError):
        M.besag_clifford_p(lambda b, g: g.random(b), 0.5, n_max=10, rung_rng=rr,
                           h=0)


def test_ladder_never_touches_the_exhaustive_shift_enumeration():
    """The ladder is for Monte Carlo nulls. The shift null is an enumeration."""
    W = _payload(n_feats=2)
    f = list(W["feats"].values())[0]
    plain = ms.glm_task(f, W["window"], W["counts"], W["offset"], W["n_surr"],
                        lambda lag: np.random.default_rng(SEED), None, seed=SEED)
    lad = ms.glm_task(f, W["window"], W["counts"], W["offset"], W["n_surr"],
                      lambda lag: np.random.default_rng(SEED),
                      dict(M.LADDER_DEFAULTS, n_max=W["n_surr"]), seed=SEED)
    for a, b in zip(plain, lad):
        assert a["p_circular_shift"] == b["p_circular_shift"], \
            "the ladder changed the exhaustive circular-shift p"
        assert a["n_surrogates"] == b["n_surrogates"]
        assert "ladder_stop" not in a and "ladder_stop" in b


def test_ladder_n_max_depends_only_on_the_test_key():
    """No rank-based escalation: budget is a function of the key, full stop."""
    cfgL = dict(M.LADDER_DEFAULTS, n_max=1000, n_max_by_kind={"mark_mag": 250})
    k1 = M.test_key(SEED, "f", "glm", lag=0, null_type="mc")
    k2 = M.test_key(SEED, "f", "mark_mag", null_type="mc")
    assert M.ladder_n_max(cfgL, k1) == 1000
    assert M.ladder_n_max(cfgL, k2) == 250
    # the signature admits nothing else -- no statistic, no p, no rank
    import inspect
    assert list(inspect.signature(M.ladder_n_max).parameters) == \
        ["ladder_cfg", "key"]


def test_ladder_floor_is_the_cap_not_the_draws_actually_made():
    """A test that stopped at rung 1 could still have gone to the cap."""
    t = {"test": "glm_poisson_offset_etas", "p_circular_shift": 0.5,
         "n_surrogates": 200, "null": "max(circular-shift, block-bootstrap)",
         "ladder_stop": {"n_max": 1000, "n_drawn": 200}}
    fl = ms.test_floor(t, 1000)
    assert t["floor_monte_carlo"] == pytest.approx(1.0 / 1001.0)
    assert t["floor_enumeration"] == pytest.approx(1.0 / 201.0)
    assert fl == pytest.approx(1.0 / 201.0)      # the LARGER of the two


def test_ladder_uniformity_audit_fast_mode_passes():
    """Popper's binding acceptance test, suite-sized. Full run: engine/audit_ladder."""
    from engine import audit_ladder

    out = audit_ladder.run_audit(n_tests=5000, n_max=500, verbose=False)
    assert out["validity_pass"], out          # D+ below the one-sided KS critical
    assert out["agree_pass"], out             # >=99% within 3 combined SE
    assert out["exact_on_cap_pass"], out      # cap branch is bit-identical
    assert out["draw_saving"] > 0.2, out      # and it actually saves work


# ============================================================================
# (d) CHECKPOINTS, RESUME AND FAILURE
# ============================================================================
def test_parallel_resume_skips_done_tasks_and_keeps_their_results(tmp_path):
    W = _payload(n_feats=2)
    keys = _keys(W)
    ck = _ckpt(tmp_path, "session_resume")

    # a "killed" run that got two tasks done
    first = keys[:2]
    n1 = ms._run_tasks_parallel(ck, first, W, 2, verbose=False)
    assert n1 == 2 and set(ck.state["results"]) == set(first)
    snapshot = json.dumps(ck.state["results"], sort_keys=True)

    # reload from disk exactly as a resumed invocation would
    again = ms.Checkpoint.load(ck.path)
    assert json.dumps(again.state["results"], sort_keys=True) == snapshot

    n2 = ms._run_tasks_parallel(again, keys, W, 3, verbose=False)
    assert n2 == len(keys) - 2, "resume recomputed already-checkpointed tasks"
    # per-task cost is recorded for every task the parent accepted, and survives
    # the reload -- so a resumed run can still be diagnosed
    assert set(again.state["task_seconds"]) == set(keys)
    assert set(again.state["results"]) == set(keys)
    # the survivors of the first run must be untouched, not recomputed
    for k in first:
        assert again.state["results"][k] == json.loads(snapshot)[k]
    # completed_tasks must not gain duplicates across the resume
    assert len(again.state["completed_tasks"]) == \
        len(set(again.state["completed_tasks"]))


def test_worker_exception_names_the_failing_task(tmp_path):
    W = _payload(n_feats=1)
    ck = _ckpt(tmp_path, "session_boom")
    bad = "glm:no_such_feature"
    with pytest.raises(RuntimeError) as exc:
        ms._run_tasks_parallel(ck, [bad], W, 2, verbose=False)
    assert bad in str(exc.value), "a worker failure must name the feature/test"
    assert "worker" in str(exc.value).lower()
    # and nothing partial was written for it
    assert not ck.done(bad)


def test_worker_wrapper_returns_the_traceback_rather_than_dying():
    ms._worker_init(_payload(n_feats=1))
    key, res, err, secs = ms.worker_run_task("marks:not_a_feature")
    assert key == "marks:not_a_feature" and res is None
    assert err and "Traceback" in err and "not_a_feature" in err
    assert secs >= 0.0


def test_bulk_invariant_refuses_to_report_a_short_result_set(tmp_path):
    """n_results == n_tasks is asserted BEFORE anything is written."""
    W = _payload(n_feats=2)
    keys = _keys(W)
    ck = _ckpt(tmp_path, "session_short")
    ms._run_tasks_parallel(ck, keys[:1], W, 2, verbose=False)
    missing = [k for k in keys if not ck.done(k)]
    assert len(missing) == len(keys) - 1
    # this is the exact guard mine_session.run() applies
    with pytest.raises(RuntimeError, match="incomplete"):
        if missing:
            raise RuntimeError(
                f"mine session incomplete: {len(missing)} of {len(keys)} declared "
                f"tasks have no result")


def test_only_the_parent_writes_the_checkpoint(tmp_path):
    """Workers get a payload, not a path. A worker cannot write even by accident."""
    W = _payload(n_feats=1)
    assert not any(isinstance(v, str) and ("checkpoint" in v or v.endswith(".json"))
                   for v in W.values()), "payload leaked a file path to the workers"
    assert "ckpt" not in W and "session_dir" not in W
    ck = _ckpt(tmp_path, "session_writer")
    before = os.path.getmtime(ck.path) if os.path.exists(ck.path) else None
    ms._worker_init(W)
    ms.worker_run_task("glm:" + next(iter(W["feats"])))
    after = os.path.getmtime(ck.path) if os.path.exists(ck.path) else None
    assert before == after


def test_ledger_record_states_the_declared_count_explicitly():
    cfg = {"preset": "unit", "n_surrogates": 10, "seed": 1}
    rec = ms.ledger_record(cfg, 391, "engine/out/mine/session_z")
    assert rec["n_declared_tests"] == 391
    assert rec["n_tests"] == 391
    assert rec["kind"] == "mine" and rec["config"] == cfg
    assert "\\" not in rec["session_dir"]
    json.dumps(rec)                       # must be ledger-serialisable


# ============================================================================
# (e) PHASE 1b -- the period scan is decomposed, and the decomposition is invisible
#
# These three are the forcing functions for the design. If seeding were per CHUNK
# instead of per SURROGATE INDEX, (b) would fail; if the sequential driver used a
# different stream from the pool, (a) would fail; if the assembly dropped or
# reordered a chunk, (c) would fail.
# ============================================================================
def _period_keys(W):
    return ms.period_task_keys(W["cfg"], W["n_surr"])


def _run_sequential(ck, keys, W):
    """Exactly what mine_session.run() does for these keys at --jobs 1."""
    for k in keys:
        if ck.done(k):
            continue
        ck.record_seconds(k, 0.0)
        ck.put(k, ms.dispatch_task(k, W))


def _assemble(results, W, chunk=None):
    return ms.period_finish(W["counts"], W["offset"], W["days"], W["cfg"],
                            results["period_obs"],
                            *ms.collect_period_maxima(results, W["cfg"],
                                                      W["n_surr"], chunk))


def test_period_scan_jobs1_equals_jobs4_bit_for_bit(tmp_path):
    """The headline claim of phase 1b: scheduling cannot reach the answer."""
    W = _payload(n_feats=1)
    keys = _period_keys(W)
    assert len(keys) > 2, "the period scan must actually be decomposed"

    ck1 = _ckpt(tmp_path, "session_seq")
    _run_sequential(ck1, keys, W)
    ck4 = _ckpt(tmp_path, "session_par4")
    ms._run_tasks_parallel(ck4, keys, W, 4, verbose=False)

    r1 = {k: ck1.state["results"][k] for k in keys}
    r4 = {k: ck4.state["results"][k] for k in keys}
    assert json.dumps(r1, sort_keys=True) == json.dumps(r4, sort_keys=True), \
        "period subtask results differ between --jobs 1 and --jobs 4"
    assert json.dumps(_assemble(r1, W), sort_keys=True) == \
        json.dumps(_assemble(r4, W), sort_keys=True), \
        "assembled period scan differs between --jobs 1 and --jobs 4"


def test_period_chunk_size_invariance():
    """Seeding is per SURROGATE INDEX, so chunk size is an execution knob only.

    chunk=50 vs chunk=200 as specified, plus a deliberately ragged 7 vs 13 so the
    invariance is not an artefact of one chunking dividing the other.
    """
    W = _payload(n_feats=1, n_surr=120)
    ref = None
    for chunk in (50, 200, 7, 13):
        seqs = M.period_seed_seqs(W["seed"])
        periods = ms.period_grid(W["cfg"])
        got = {}
        for nt in M.PERIOD_NULLS:
            parts = [M.period_surrogate_maxima(W["days"], W["resid"], periods, nt,
                                               a, b, seqs[nt])
                     for a, b in M.period_chunks(M.period_n_mc(W["n_surr"]), chunk)]
            got[nt] = np.concatenate(parts)
        if ref is None:
            ref = got
            assert ref["ar1"].size == M.period_n_mc(W["n_surr"])
            assert not np.array_equal(ref["ar1"], ref["permutation"])
        for nt in M.PERIOD_NULLS:
            assert np.array_equal(ref[nt], got[nt]), \
                f"chunk={chunk} changed the {nt} surrogates -- seeding is not " \
                f"per surrogate index"

    # and end to end, through the public scan, at ZERO tolerance
    a = M.period_scan(W["days"], W["resid"], ms.period_grid(W["cfg"]), W["n_surr"],
                      W["seed"], n_peaks=3, verbose=False, chunk=50)
    b = M.period_scan(W["days"], W["resid"], ms.period_grid(W["cfg"]), W["n_surr"],
                      W["seed"], n_peaks=3, verbose=False, chunk=200)
    assert json.dumps(a, sort_keys=True) == json.dumps(b, sort_keys=True)


def test_chunked_period_scan_equals_the_unchunked_reference(tmp_path):
    """Chunked session path == single-process `period_task`, exactly. No tolerance."""
    W = _payload(n_feats=1, n_surr=120)
    keys = _period_keys(W)
    ck = _ckpt(tmp_path, "session_chunked")
    _run_sequential(ck, keys, W)
    chunked = _assemble({k: ck.state["results"][k] for k in keys}, W)

    reference = ms.period_task(W["counts"], W["offset"], W["days"], W["resid"],
                               W["cfg"], W["n_surr"], W["seed"], verbose=False,
                               chunk=10 ** 6)          # one chunk = no chunking
    assert json.dumps(chunked, sort_keys=True) == \
        json.dumps(reference, sort_keys=True)
    assert chunked["scan"]["n_mc"] == M.period_n_mc(W["n_surr"])
    for pk in chunked["peaks"]:
        assert pk["n_surrogates"] == M.period_n_mc(W["n_surr"])


def test_period_assembly_refuses_a_dropped_or_short_chunk(tmp_path):
    """FAILURE-FIRST: a missing chunk names itself and stops the run.

    A silently dropped chunk would shift every p-value in the scan by a fraction of
    a rank, which is the kind of error that never surfaces as a crash.
    """
    W = _payload(n_feats=1)
    keys = _period_keys(W)
    ck = _ckpt(tmp_path, "session_drop")
    _run_sequential(ck, keys, W)
    res = dict(ck.state["results"])

    victim = [k for k in keys if k.startswith("psurr:ar1:")][-1]
    dropped = {k: v for k, v in res.items() if k != victim}
    with pytest.raises(RuntimeError) as exc:
        ms.collect_period_maxima(dropped, W["cfg"], W["n_surr"])
    assert victim in str(exc.value) and "ar1" in str(exc.value)

    short = json.loads(json.dumps(res))
    short[victim]["maxima"] = short[victim]["maxima"][:-1]
    with pytest.raises(RuntimeError, match="Refusing to price"):
        ms.collect_period_maxima(short, W["cfg"], W["n_surr"])

    # and the counted invariant is ALSO enforced one level down, in period_assemble
    n_mc = M.period_n_mc(W["n_surr"])
    with pytest.raises(RuntimeError, match="collected"):
        M.period_assemble(np.zeros(5), np.arange(1.0, 6.0), [1],
                          {"ar1": np.zeros(n_mc - 1),
                           "permutation": np.zeros(n_mc)}, 0.1, n_mc)
    with pytest.raises(RuntimeError, match="NO surrogate maxima"):
        M.period_assemble(np.zeros(5), np.arange(1.0, 6.0), [1],
                          {"ar1": np.zeros(n_mc)}, 0.1, n_mc)


def test_period_decomposition_actually_shrinks_the_largest_task():
    """The point of phase 1b, asserted as an invariant rather than a benchmark.

    No period subtask may carry more than `PERIOD_SURROGATE_CHUNK` surrogates, and
    the number of subtasks must scale with the surrogate budget -- otherwise the
    Amdahl ceiling that motivated this work quietly comes back.
    """
    for n_surr, expect in ((200, 2 * (200 // M.PERIOD_SURROGATE_CHUNK) + 1),
                           (10000, 2 * (M.PERIOD_N_MC_CAP
                                        // M.PERIOD_SURROGATE_CHUNK) + 1)):
        keys = ms.period_task_keys({"n_peaks": 5, "n_periods": 100}, n_surr)
        assert len(keys) == expect, (n_surr, len(keys))
    bounds = M.period_chunks(M.period_n_mc(10000))
    assert max(b - a for a, b in bounds) <= M.PERIOD_SURROGATE_CHUNK
    assert sum(b - a for a, b in bounds) == M.period_n_mc(10000)
    # the two nulls must not share a stream
    s = M.period_seed_seqs(SEED)
    assert M.test_key_digest(M.test_key(SEED, "period_scan", "period",
                                        null_type="ar1")) != \
        M.test_key_digest(M.test_key(SEED, "period_scan", "period",
                                     null_type="permutation"))
    assert s["ar1"].spawn_key != s["permutation"].spawn_key


def test_period_key_schema_extension_did_not_rekey_phase1_digests():
    """Compatibility clause: no field was added to TEST_KEY_FIELDS.

    The chunk/surrogate index rides the SPAWN-KEY child axis instead, so every test
    digest phase 1 declared is byte-identical today. These are the phase-1 values.
    """
    assert M.TEST_KEY_FIELDS == ("master_seed", "feature", "kind", "lag", "rung",
                                "null_type", "region", "bin_width")
    k = M.test_key(20260811, "moon_synodic_phase", "glm", lag=3,
                   null_type="block_bootstrap")
    # verified against `git show cca6432:engine/mine.py` (the phase-1 commit)
    assert M.test_key_digest(k) == (
        "311f3760df3a42e4d743c1d38e8ca2ea21d90a999f4b3e5be69025fbb407ee20")


def test_resolve_jobs():
    assert ms.resolve_jobs(1) == 1
    assert ms.resolve_jobs(4) == 4
    assert ms.resolve_jobs(0) == max(1, (os.cpu_count() or 1) - 2)
    assert ms.resolve_jobs(-3) == 1
