"""§P7-15's recovery-versus-amplitude curve: the estimator, not the pipeline.

The pipeline is `mine_session.run` and the plant machinery is `gate_r1`, both
already covered. What is new here is the ARITHMETIC that turns 120 binomial
observations into the sentence "the formula is (or is not) anti-conservative by
Nx" -- and a sign or scale error there would produce a confident wrong answer to
the exact question §P7-15 asked. So: the predicted curve is pinned against the
ledger's own published values, the estimator is pinned by recovering a known
effective floor from data generated under it, and the degenerate cases are
pinned to report BOUNDS rather than point estimates.
"""

import math

import numpy as np
import pytest

from engine import floors
from engine import gate_r1 as G
from engine import recovery_curve as RC


# ================================================= the predicted curve, pinned =
def test_predicted_power_reproduces_the_ledger_published_values():
    """§P7-15: "0.800 at 1x the floor, 0.9992 at 1.5x, and 1.0000 at 2x".

    These three numbers are in the ledger, computed by the adjudicator from the
    §P7-12(a) formula. If this module's derivation of the same curve ever stops
    reproducing them, this module is wrong -- the ledger is the reference.
    """
    assert RC.predicted_power(1.0) == pytest.approx(0.800, abs=5e-4)
    assert RC.predicted_power(1.5) == pytest.approx(0.9992, abs=5e-5)
    assert RC.predicted_power(2.0) == pytest.approx(1.0000, abs=5e-5)
    assert RC.predicted_power(3.0) == pytest.approx(1.0000, abs=1e-9)


def test_predicted_power_at_1x_IS_the_floors_own_80_percent_definition():
    """The formula's floor is by construction the 80%-power amplitude."""
    assert RC.predicted_power(1.0) == pytest.approx(floors.POWER, abs=1e-9)


def test_predicted_power_is_monotone_in_amplitude():
    ks = [0.25, 0.5, 1.0, 1.5, 2.0, 3.0]
    ps = [RC.predicted_power(k) for k in ks]
    assert ps == sorted(ps)
    assert ps[0] < 0.05          # a quarter-floor plant is nearly invisible


# ============================================ the effective-floor MLE, pinned ==
def _synthetic(a_eff, amplitudes, n=200, seed=5):
    """Binomial data generated BY the fitted family at a known `a_eff`."""
    rng = np.random.default_rng(seed)
    hits = [int(rng.binomial(n, RC.effective_floor_ratio(x, a_eff)))
            for x in amplitudes]
    return list(amplitudes), [n] * len(amplitudes), hits


def test_the_fit_recovers_a_known_effective_floor():
    truth = 0.30
    amps = [0.15, 0.225, 0.30, 0.45]
    fit = RC.fit_effective_floor(*_synthetic(truth, amps))
    assert fit["converged"] is True
    assert fit["degenerate"] is False
    assert fit["a_eff"] == pytest.approx(truth, rel=0.10)
    lo, hi = fit["a_eff_ci95"]
    assert lo < truth < hi


def test_the_fit_recovers_a_floor_TWICE_the_formulas_and_says_so():
    """The exact scenario §P7-15 hypothesises, run through the estimator.

    Data generated at an effective floor 2x the formula's must come back as
    an inflation factor of ~2 -- otherwise the module cannot tell explanation
    (b) from explanation (a), which is its only job.
    """
    a_formula = 0.1495                       # arm (i)'s formula floor
    truth = 2.0 * a_formula
    amps = [a_formula * k for k in (1.0, 1.5, 2.0, 3.0)]
    fit = RC.fit_effective_floor(*_synthetic(truth, amps, seed=11))
    assert fit["a_eff"] / a_formula == pytest.approx(2.0, rel=0.12)


def test_a_correct_formula_comes_back_as_an_inflation_of_one():
    a_formula = 0.1495
    amps = [a_formula * k for k in (1.0, 1.5, 2.0, 3.0)]
    fit = RC.fit_effective_floor(*_synthetic(a_formula, amps, seed=13))
    assert fit["a_eff"] / a_formula == pytest.approx(1.0, rel=0.12)


def test_all_hits_and_all_misses_return_a_BOUND_not_a_point_estimate():
    """A saturated arm has a monotone likelihood; the MLE sits on a boundary.

    Arm (ii)'s regional plants are large enough that 40/40 is a live outcome.
    Reporting the boundary value as if it were an estimate would be a number
    with no evidence under it, so it is refused and labelled.
    """
    amps = [0.4, 0.6, 0.8, 1.2]
    all_hit = RC.fit_effective_floor(amps, [10] * 4, [10] * 4)
    assert all_hit["degenerate"] is True
    assert all_hit["a_eff"] is None
    assert "BELOW the smallest amplitude" in all_hit["bound"]
    all_miss = RC.fit_effective_floor(amps, [10] * 4, [0] * 4)
    assert all_miss["degenerate"] is True
    assert all_miss["a_eff"] is None
    assert "ABOVE the largest amplitude" in all_miss["bound"]


def test_amplitude_at_power_inverts_the_fitted_curve():
    a_eff = 0.27
    assert RC.amplitude_at_power(a_eff, 0.80) == pytest.approx(a_eff, rel=1e-9)
    a95 = RC.amplitude_at_power(a_eff, 0.95)
    assert a95 > a_eff
    assert RC.effective_floor_ratio(a95, a_eff) == pytest.approx(0.95, abs=1e-9)


# ================================================== interval and threshold code
def test_wilson_never_returns_a_zero_width_interval_at_the_boundary():
    lo, hi = RC.wilson(10, 10)
    assert hi == pytest.approx(1.0, abs=1e-9)
    assert lo < 0.75                      # 10/10 does NOT establish >= 95%
    lo0, hi0 = RC.wilson(0, 10)
    assert lo0 == pytest.approx(0.0, abs=1e-9) and hi0 > 0.25
    assert RC.wilson(8, 10)[0] < 0.8 < RC.wilson(8, 10)[1]


def test_threshold_interpolation_crosses_reports_bounds_and_never_extrapolates():
    crossing = RC.interpolate_threshold(
        [(0.10, 0.4), (0.20, 0.6), (0.30, 1.0)], 0.80)
    assert crossing["amplitude"] == pytest.approx(0.25)
    assert crossing["bracket"] == [0.20, 0.30]

    already = RC.interpolate_threshold([(0.10, 0.9), (0.20, 1.0)], 0.80)
    assert already["amplitude"] is None
    assert already["at_or_below"] == 0.10
    assert "bound, not an interpolation" in already["reason"]

    never = RC.interpolate_threshold([(0.10, 0.2), (0.20, 0.5)], 0.80)
    assert never["amplitude"] is None
    assert never["above"] == 0.20
    assert "lower bound" in never["reason"]


# ============================================ plant construction at each factor
def _prep(n_days=2000, n_cells=8, rate=3.0):
    theta = np.mod(2 * np.pi * np.arange(n_days) / 29.53, 2 * np.pi)
    rate_w = np.full((n_cells, n_days), rate, dtype=np.float64)

    class F:
        name = G.ARM_I_FEATURE
        kind = "phase"
        values = theta
        period_hint = 29.53
        block_days = 60.0

    class F3(F):
        name = G.ARM_III_FEATURE

    return {"feats": [F(), F3()], "window": slice(0, n_days), "rate_w": rate_w,
            "offset": rate_w.sum(axis=0), "y": np.zeros((n_cells, n_days)),
            "counts": rate_w.sum(axis=0),
            "marks": {"mag": np.full(100, 4.7), "depth": np.full(100, 10.0)}}


@pytest.mark.parametrize("k", [1.0, 1.5, 2.0, 3.0])
def test_each_swept_factor_plants_at_exactly_that_multiple_of_the_floor(k):
    prep = _prep()
    part = {"R": 2, "region_of_cell": np.array([0, 0, 0, 0, 1, 1, 1, 1])}
    _mod, reps, planted = RC.build_plant(prep, part, "i", k)
    r = reps[0]
    assert r["amplitude_over_floor"] == pytest.approx(k)
    assert r["planted_amplitude"] == pytest.approx(
        k * r["operative_floor_A_min"])
    assert planted["truth_amplitude"] == pytest.approx(r["planted_amplitude"])


def test_sub_2x_cells_are_labelled_as_a_deliberate_P7_8d_departure():
    """§P7-8(d) says plant at >= 2x. This sweep goes below ON PURPOSE, and the
    label is what stops a low-amplitude miss being read as an instrument fault."""
    prep = _prep()
    part = {"R": 2, "region_of_cell": np.array([0, 0, 0, 0, 1, 1, 1, 1])}
    for k, want in ((1.0, False), (1.5, False), (2.0, True), (3.0, True)):
        _m, reps, _p = RC.build_plant(prep, part, "i", k)
        assert reps[0]["p7_8d_compliant"] is want
        assert reps[0]["declared_factor"] == pytest.approx(k)
        if not want:
            assert "POWER measurement" in reps[0]["p7_8d_note"]
            assert "NOT an instrument verdict" in reps[0]["p7_8d_note"]
        else:
            assert "IS an instrument verdict" in reps[0]["p7_8d_note"]


def test_the_regional_arm_declares_no_truth_amplitude():
    """§P7-1(d): the 2R-df sum is a DETECTION statistic with no single amplitude,
    so the arm must assert detection and never an amplitude ratio."""
    prep = _prep()
    part = {"R": 2, "region_of_cell": np.array([0, 0, 0, 0, 1, 1, 1, 1])}
    _mod, reps, planted = RC.build_plant(prep, part, "ii", 1.5)
    assert planted["truth_amplitude"] is None
    assert planted["test_kind"] == "regsum_score_2Rdf"
    assert len(reps) == 2
    for r in reps:
        assert r["amplitude_over_floor"] == pytest.approx(1.5)


# ====================================================== the (a)/(b)/(c) verdict
def _arm(ratio_med, inflation):
    cells = [{"factor": k, "planted_amplitude": 0.15 * k,
              "operative_floor_A_min": 0.15, "n": 10, "n_detected": 8,
              "recovery_rate": 0.8, "wilson95": [0.5, 0.94],
              "predicted_power": RC.predicted_power(k),
              "p7_8d_compliant": k >= 2, "amplitude_ratio_median": ratio_med,
              "amplitude_ratio_n": 10, "source": ["x"]}
             for k in (1.0, 1.5, 2.0, 3.0)]
    e = {"label": "t", "cells": cells, "a_min_formula": 0.15, "fit": {}}
    if inflation is not None:
        e["a_eff_over_a_formula"] = inflation
    return e


def test_verdict_b_when_plants_land_where_labelled_but_the_floor_is_inflated():
    v = RC.classify({"i": _arm(1.00, 2.1), "iii": _arm(1.01, 1.9)})
    assert v["choice"] == "b"
    assert v["arms_with_inflated_floor"] == ["i", "iii"]
    assert v["arms_with_mislabelled_plants"] == []
    assert "ANTI-CONSERVATIVE" in v["headline"]


def test_verdict_a_when_the_plants_did_not_land_where_labelled():
    v = RC.classify({"i": _arm(0.52, 1.0), "iii": _arm(0.49, 1.05)})
    assert v["choice"] == "a"
    assert v["arms_with_mislabelled_plants"] == ["i", "iii"]
    assert "labelling" in v["headline"]


def test_verdict_c_when_only_some_arms_show_an_inflated_floor():
    v = RC.classify({"i": _arm(1.00, 2.1), "iii": _arm(1.00, 1.0)})
    assert v["choice"] == "c"
    assert v["arms_with_inflated_floor"] == ["i"]


def test_verdict_none_when_the_formula_is_vindicated():
    v = RC.classify({"i": _arm(1.00, 1.02), "iii": _arm(0.99, 0.97)})
    assert v["choice"] == "none"
    assert "neither" in v["headline"]


def test_an_unresolved_amplitude_arm_abstains_rather_than_voting():
    """Arm (ii) reports no amplitude by rule, so it can neither confirm nor
    deny explanation (a); saying so beats defaulting it to 'fine'."""
    v = RC.classify({"ii": _arm(None, None)})
    assert v["per_arm"]["ii"]["plants_delivered_as_labelled"] is None
    assert v["per_arm"]["ii"]["formula_anti_conservative"] is None
    assert "UNRESOLVED" in v["per_arm"]["ii"]["note"]
    assert v["choice"] == "none"


# ============================================================ reuse and sandbox
def test_the_reused_gate_cells_are_labelled_with_their_source():
    prog = {"cells": {}, "plant_reports": {}}
    n = RC.reuse_gate_cells(prog)
    assert n >= 0
    for key, rec in prog["cells"].items():
        assert key.startswith("curve_") and "_2.0x_" in key
        assert rec["source"] == "gate_r1"
        assert rec["factor"] == 2.0
        assert "progress.json" in rec["source_note"]


def test_the_curve_runs_in_the_same_sandbox_as_the_gate():
    import os
    info = G.assert_sandboxed(
        os.path.join(G.SANDBOX_SESSIONS, "session_curve_i_1.0x_000"),
        G.SANDBOX_LEDGER)
    assert "gate_r1" in info["session_dir"]
    assert info["ledger"].endswith("EXPLORE_COUNT_SANDBOX.jsonl")
